### ISSUE TITLE
Suggestion: Menu placement

### ISSUE THREAD

**Issue by The-Faulty** [jordanreger/LTX#3]
Have the menu options slide out to the left of the 3 bar menu button, rather than the current side bar, in order to prevent overlapping the 3 streams.

**Comment by jordanreger** [comment]
[f75382d](https://github.com/jordanreger/LTX/commit/f75382d8efbb5488983a703de4624e286ce086c7) should minimize this issue. 

The menu component is summoned by clicking three dots and closed by clicking anywhere outside. The menu width and height are set by `min-content` which should constrict the dimensions to only what's necessary.
